apiVersion: 1

datasources:
- name: Prometheus
  type: prometheus
  uid: prometheus
  access: proxy
  orgId: 1
  version: 1
  url: http://serversage-prometheus:9090
  basicAuth: false
  isDefault: false
  editable: true
  jsonData:
    httpMethod: GET