apiVersion: 1

datasources:
- name: Tempo
  type: tempo
  uid: tempo
  access: proxy
  orgId: 1
  apiVersion: 1
  url: http://tempo:3200
  basicAuth: false
  isDefault: false
  editable: true
  jsonData:
    httpMethod: GET
    serviceMap:
      datasourceUid: prometheus
    streamingEnabled:
      search: true