{
 "title": "Slow queries",
 "description": "This dashboard works with postgres_exporter for prometheus",
 "tags": [
  "postgres",
  "db",
  "stats"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "15m",
 "templating": {
  "list": [
   { "name": "DS_PROMETHEUS", "label": "datasource", "query": "prometheus" },
   { "name": "interval", "label": "Interval", "query": "1s,5s,1m,5m,1h,6h,1d" },
   {
    "name": "namespace",
    "label": "Namespace",
    "query": "query_result(pg_exporter_last_scrape_duration_seconds)"
   },
   {
    "name": "release",
    "label": "Release",
    "query": "query_result(pg_exporter_last_scrape_duration_seconds{kubernetes_namespace=\"$namespace\"})"
   },
   {
    "name": "instance",
    "label": "Instance",
    "query": "query_result(pg_up{release=\"$release\"})"
   },
   { "name": "datname", "label": "Database", "query": "label_values(datname)" },
   {
    "name": "mode",
    "label": "Lock table",
    "query": "label_values({mode=~\"accessexclusivelock|accesssharelock|exclusivelock|rowexclusivelock|rowsharelock|sharelock|sharerowexclusivelock|shareupdateexclusivelock\"}, mode)"
   }
  ]
 },
 "panels": [
  { "title": "pg state statements", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }, "repeat": "interval" },
  {
   "title": "Total Connections",
   "type": "gauge",
   "description": "total connection by state of query",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(sum by(state) (pg_stat_activity_count{instance=\"$instance\", datname=~\"$datname\"})) > 0",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Excessive Queries by Database",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count by (datname) (pg_stat_statements_calls{instance=\"$instance\",datname=~\"$datname\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total Users",
   "type": "bargauge",
   "description": "This system view provides information about current database activity, including user names and query execution details. ",
   "gridPos": { "h": 2, "w": 6, "x": 0, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (rolname) ((pg_stat_activity_count{instance=\"$instance\",datname=~\"$datname\"}))",
     "legendFormat": "{{rolname}}"
    }
   ]
  },
  {
   "title": "Last 10 executed queries",
   "type": "table",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "pg_stat_statements_calls{instance=\"$instance\",datname=~\"$datname\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Settings", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 } },
  {
   "title": "Rate of Query calls by 5m",
   "type": "timeseries",
   "description": "Number of times query called by user",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 21 },
   "targets": [
    {
     "expr": "rate(pg_stat_statements_calls{instance=\"$instance\", rolname!=\"postgres_exporter\"}[5m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Top 10 Queries by Total Execution Time",
   "type": "timeseries",
   "description": "Displays the top 10 queries with the highest total execution time across the selected instance and database. This helps identify performance bottlenecks in your PostgreSQL queries.",
   "gridPos": { "h": 15, "w": 24, "x": 0, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "(topk(10, pg_stat_statements_total_time_seconds{instance=\"$instance\", datname=~\"$datname\"}))"
    }
   ]
  }
 ]
}